/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGCFFI


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif




#ifdef __cplusplus
#  define EXTERN   extern "C"
#else
#  define EXTERN   extern
#endif

#define EXPORT   EXTERN SWIGEXPORT

#include <string.h>



#ifdef __cplusplus
#  define EXTERN   extern "C"
#else
#  define EXTERN   extern
#endif

#define EXPORT   EXTERN SWIGEXPORT

#include <string.h>
#include <stdlib.h>



#ifndef _FORMAT_H
#define _FORMAT_H

#include "journal.h"
#include "valexpr.h"
#include "walk.h"


EXPORT std::string *_wrap_truncated__SWIG_0 (std::string *larg1, unsigned int larg2, int larg3) {
  std::string * lresult = (std::string *)0 ;
  std::string *arg1 = 0 ;
  unsigned int arg2 ;
  int arg3 ;
  std::string result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  try {
    result = ledger::truncated((std::string const &)*arg1,arg2,arg3);
    lresult = new std::string(result);
    return lresult;
  } catch (...) {
    return (std::string *)0;
  }
}


EXPORT std::string *_wrap_truncated__SWIG_1 (std::string *larg1, unsigned int larg2) {
  std::string * lresult = (std::string *)0 ;
  std::string *arg1 = 0 ;
  unsigned int arg2 ;
  std::string result;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    result = ledger::truncated((std::string const &)*arg1,arg2);
    lresult = new std::string(result);
    return lresult;
  } catch (...) {
    return (std::string *)0;
  }
}


EXPORT std::string *_wrap_partial_account_name (account_t *larg1, unsigned int larg2) {
  std::string * lresult = (std::string *)0 ;
  account_t *arg1 = 0 ;
  unsigned int arg2 ;
  std::string result;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    result = ledger::partial_account_name((account_t const &)*arg1,arg2);
    lresult = new std::string(result);
    return lresult;
  } catch (...) {
    return (std::string *)0;
  }
}


EXPORT ledger::format_transactions *_wrap_new_format_transactions (std::ostream *larg1, std::string *larg2) {
  ledger::format_transactions * lresult = (ledger::format_transactions *)0 ;
  std::ostream *arg1 = 0 ;
  std::string *arg2 = 0 ;
  ledger::format_transactions *result = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    result = (ledger::format_transactions *)new ledger::format_transactions(*arg1,(std::string const &)*arg2);
    lresult = result;
    return lresult;
  } catch (...) {
    return (ledger::format_transactions *)0;
  }
}


EXPORT void _wrap_format_transactions_flush (ledger::format_transactions *larg1) {
  ledger::format_transactions *arg1 = (ledger::format_transactions *) 0 ;
  
  arg1 = larg1;
  try {
    (arg1)->flush();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_format_transactions___funcall__ (ledger::format_transactions *larg1, transaction_t *larg2) {
  ledger::format_transactions *arg1 = (ledger::format_transactions *) 0 ;
  transaction_t *arg2 = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    (arg1)->operator ()(*arg2);
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_delete_format_transactions (ledger::format_transactions *larg1) {
  ledger::format_transactions *arg1 = (ledger::format_transactions *) 0 ;
  
  arg1 = larg1;
  try {
    delete arg1;
    
  } catch (...) {
    
  }
}


EXPORT ledger::format_entries *_wrap_new_format_entries (std::ostream *larg1, std::string *larg2) {
  ledger::format_entries * lresult = (ledger::format_entries *)0 ;
  std::ostream *arg1 = 0 ;
  std::string *arg2 = 0 ;
  ledger::format_entries *result = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    result = (ledger::format_entries *)new ledger::format_entries(*arg1,(std::string const &)*arg2);
    lresult = result;
    return lresult;
  } catch (...) {
    return (ledger::format_entries *)0;
  }
}


EXPORT void _wrap_format_entries_format_last_entry (ledger::format_entries *larg1) {
  ledger::format_entries *arg1 = (ledger::format_entries *) 0 ;
  
  arg1 = larg1;
  try {
    (arg1)->format_last_entry();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_format_entries_flush (ledger::format_entries *larg1) {
  ledger::format_entries *arg1 = (ledger::format_entries *) 0 ;
  
  arg1 = larg1;
  try {
    (arg1)->flush();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_format_entries___funcall__ (ledger::format_entries *larg1, transaction_t *larg2) {
  ledger::format_entries *arg1 = (ledger::format_entries *) 0 ;
  transaction_t *arg2 = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    (arg1)->operator ()(*arg2);
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_delete_format_entries (ledger::format_entries *larg1) {
  ledger::format_entries *arg1 = (ledger::format_entries *) 0 ;
  
  arg1 = larg1;
  try {
    delete arg1;
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_print_entry__SWIG_0 (std::ostream *larg1, entry_base_t *larg2, std::string *larg3) {
  std::ostream *arg1 = 0 ;
  entry_base_t *arg2 = 0 ;
  std::string *arg3 = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  try {
    ledger::print_entry(*arg1,(entry_base_t const &)*arg2,(std::string const &)*arg3);
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_print_entry__SWIG_1 (std::ostream *larg1, entry_base_t *larg2) {
  std::ostream *arg1 = 0 ;
  entry_base_t *arg2 = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    ledger::print_entry(*arg1,(entry_base_t const &)*arg2);
    
  } catch (...) {
    
  }
}


EXPORT int _wrap_disp_subaccounts_p__SWIG_0 (account_t *larg1, item_predicate< account_t > *larg2, account_t **larg3) {
  int lresult = (int)0 ;
  account_t *arg1 = 0 ;
  item_predicate< account_t > *arg2 = 0 ;
  account_t **arg3 = 0 ;
  bool result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  try {
    result = (bool)ledger::disp_subaccounts_p((account_t const &)*arg1,(item_predicate< account_t > const &)*arg2,(account_t const *&)*arg3);
    lresult = (int)result;
    return lresult;
  } catch (...) {
    return (int)0;
  }
}


EXPORT int _wrap_disp_subaccounts_p__SWIG_1 (account_t *larg1) {
  int lresult = (int)0 ;
  account_t *arg1 = 0 ;
  bool result;
  
  arg1 = larg1;
  try {
    result = (bool)ledger::disp_subaccounts_p((account_t const &)*arg1);
    lresult = (int)result;
    return lresult;
  } catch (...) {
    return (int)0;
  }
}


EXPORT int _wrap_display_account (account_t *larg1, item_predicate< account_t > *larg2) {
  int lresult = (int)0 ;
  account_t *arg1 = 0 ;
  item_predicate< account_t > *arg2 = 0 ;
  bool result;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    result = (bool)ledger::display_account((account_t const &)*arg1,(item_predicate< account_t > const &)*arg2);
    lresult = (int)result;
    return lresult;
  } catch (...) {
    return (int)0;
  }
}


EXPORT void _wrap_format_account_format_set (ledger::format_account *larg1, ledger::format_t *larg2) {
  ledger::format_account *arg1 = (ledger::format_account *) 0 ;
  ledger::format_t *arg2 = (ledger::format_t *) 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    if (arg1) (arg1)->format = *arg2;
    
  } catch (...) {
    
  }
}


EXPORT ledger::format_t *_wrap_format_account_format_get (ledger::format_account *larg1) {
  ledger::format_t * lresult = (ledger::format_t *)0 ;
  ledger::format_account *arg1 = (ledger::format_account *) 0 ;
  ledger::format_t *result = 0 ;
  
  arg1 = larg1;
  try {
    result = (ledger::format_t *)& ((arg1)->format);
    lresult = result;
    return lresult;
  } catch (...) {
    return (ledger::format_t *)0;
  }
}


EXPORT ledger::format_account *_wrap_new_format_account__SWIG_0 (std::ostream *larg1, std::string *larg2, std::string *larg3) {
  ledger::format_account * lresult = (ledger::format_account *)0 ;
  std::ostream *arg1 = 0 ;
  std::string *arg2 = 0 ;
  std::string *arg3 = 0 ;
  ledger::format_account *result = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  try {
    result = (ledger::format_account *)new ledger::format_account(*arg1,(std::string const &)*arg2,(std::string const &)*arg3);
    lresult = result;
    return lresult;
  } catch (...) {
    return (ledger::format_account *)0;
  }
}


EXPORT ledger::format_account *_wrap_new_format_account__SWIG_1 (std::ostream *larg1, std::string *larg2) {
  ledger::format_account * lresult = (ledger::format_account *)0 ;
  std::ostream *arg1 = 0 ;
  std::string *arg2 = 0 ;
  ledger::format_account *result = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    result = (ledger::format_account *)new ledger::format_account(*arg1,(std::string const &)*arg2);
    lresult = result;
    return lresult;
  } catch (...) {
    return (ledger::format_account *)0;
  }
}


EXPORT void _wrap_format_account_flush (ledger::format_account *larg1) {
  ledger::format_account *arg1 = (ledger::format_account *) 0 ;
  
  arg1 = larg1;
  try {
    (arg1)->flush();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_format_account___funcall__ (ledger::format_account *larg1, account_t *larg2) {
  ledger::format_account *arg1 = (ledger::format_account *) 0 ;
  account_t *arg2 = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    (arg1)->operator ()(*arg2);
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_delete_format_account (ledger::format_account *larg1) {
  ledger::format_account *arg1 = (ledger::format_account *) 0 ;
  
  arg1 = larg1;
  try {
    delete arg1;
    
  } catch (...) {
    
  }
}


EXPORT ledger::format_equity *_wrap_new_format_equity (std::ostream *larg1, std::string *larg2, std::string *larg3) {
  ledger::format_equity * lresult = (ledger::format_equity *)0 ;
  std::ostream *arg1 = 0 ;
  std::string *arg2 = 0 ;
  std::string *arg3 = 0 ;
  ledger::format_equity *result = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  try {
    result = (ledger::format_equity *)new ledger::format_equity(*arg1,(std::string const &)*arg2,(std::string const &)*arg3);
    lresult = result;
    return lresult;
  } catch (...) {
    return (ledger::format_equity *)0;
  }
}


EXPORT void _wrap_format_equity_flush (ledger::format_equity *larg1) {
  ledger::format_equity *arg1 = (ledger::format_equity *) 0 ;
  
  arg1 = larg1;
  try {
    (arg1)->flush();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_format_equity___funcall__ (ledger::format_equity *larg1, account_t *larg2) {
  ledger::format_equity *arg1 = (ledger::format_equity *) 0 ;
  account_t *arg2 = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    (arg1)->operator ()(*arg2);
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_delete_format_equity (ledger::format_equity *larg1) {
  ledger::format_equity *arg1 = (ledger::format_equity *) 0 ;
  
  arg1 = larg1;
  try {
    delete arg1;
    
  } catch (...) {
    
  }
}


EXPORT ledger::format_error *_wrap_new_format_error__SWIG_0 (std::string *larg1, error_context *larg2) {
  ledger::format_error * lresult = (ledger::format_error *)0 ;
  std::string *arg1 = 0 ;
  error_context *arg2 = (error_context *) 0 ;
  ledger::format_error *result = 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  try {
    result = (ledger::format_error *)new ledger::format_error((std::string const &)*arg1,arg2);
    lresult = result;
    return lresult;
  } catch (...) {
    return (ledger::format_error *)0;
  }
}


EXPORT ledger::format_error *_wrap_new_format_error__SWIG_1 (std::string *larg1) {
  ledger::format_error * lresult = (ledger::format_error *)0 ;
  std::string *arg1 = 0 ;
  ledger::format_error *result = 0 ;
  
  arg1 = larg1;
  try {
    result = (ledger::format_error *)new ledger::format_error((std::string const &)*arg1);
    lresult = result;
    return lresult;
  } catch (...) {
    return (ledger::format_error *)0;
  }
}


EXPORT void _wrap_delete_format_error (ledger::format_error *larg1) {
  ledger::format_error *arg1 = (ledger::format_error *) 0 ;
  
  arg1 = larg1;
  try {
    delete arg1;
    
  } catch (...) {
    
  }
}



#endif // _FORMAT_H
  
