;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.9
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cffi:defcfun ("_wrap_timing_t_begin_set" timing_t_begin_set) :void
  (self :pointer)
  (begin :pointer))

(cffi:defcfun ("_wrap_timing_t_begin_get" timing_t_begin_get) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_timing_t_cumulative_set" timing_t_cumulative_set) :void
  (self :pointer)
  (cumulative :pointer))

(cffi:defcfun ("_wrap_timing_t_cumulative_get" timing_t_cumulative_get) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_timing_t_file_set" timing_t_file_set) :void
  (self :pointer)
  (file :pointer))

(cffi:defcfun ("_wrap_timing_t_file_get" timing_t_file_get) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_timing_t_line_set" timing_t_line_set) :void
  (self :pointer)
  (line :unsigned-long))

(cffi:defcfun ("_wrap_timing_t_line_get" timing_t_line_get) :unsigned-long
  (self :pointer))

(cffi:defcfun ("_wrap_timing_t_symbol_set" timing_t_symbol_set) :void
  (self :pointer)
  (symbol :pointer))

(cffi:defcfun ("_wrap_timing_t_symbol_get" timing_t_symbol_get) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_timing_t_category_set" timing_t_category_set) :void
  (self :pointer)
  (category :pointer))

(cffi:defcfun ("_wrap_timing_t_category_get" timing_t_category_get) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_new_timing_t__SWIG_0" new_timing_t) :pointer
  (_symbol :pointer)
  (_category :pointer))

(cffi:defcfun ("_wrap_new_timing_t__SWIG_1" new_timing_t) :pointer
  (_symbol :pointer))

(cffi:defcfun ("_wrap_delete_timing_t" delete_timing_t) :void
  (self :pointer))

(cffi:defcfun ("_wrap_timing_t_start__SWIG_0" timing_t_start) :void
  (self :pointer)
  (_file :pointer)
  (_line :unsigned-long))

(cffi:defcfun ("_wrap_timing_t_start__SWIG_1" timing_t_start) :void
  (self :pointer))

(cffi:defcfun ("_wrap_timing_t_stop" timing_t_stop) :void
  (self :pointer))


